### ISSUE TITLE
webpackerを亡き者にする

### ISSUE THREAD

**Issue by fujjima** [fujjima/fujjima-blog#44]
## Why

webpackerは見捨てられたため
https://github.com/rails/webpacker

## What

Webpackに移行する

## ToDo

- [x] Webpackerのモジュール・設定を消す
- [x] Webpacker関連ファイルの削除
  - .browserslistrc
  - babel.config.js
  - bin/webpack
  - postcss.config.js
  - config/webpack配下の各種ファイル
    - [参考](https://madogiwa0124.hatenablog.com/entry/2020/09/12/164828#:~:text=Webpacker%E9%96%A2%E9%80%A3%E3%83%95%E3%82%A1%E3%82%A4%E3%83%AB%E3%82%92%E5%89%8A%E9%99%A4%E3%81%99%E3%82%8B)
- [ ] 必要があればnodeのバージョンを上げる
- [x] 必要なモジュール・ライブラリを入れる
  - loader系
  - クライアント系
  - `dev-server`
  - その他
- [ ] webpack関連のディレクトリ構成について整理する
- [ ] webpack.config.jsを編集する
  - 編集項目について
    - entry
  - 参考
    - https://engineer.crowdworks.jp/entry/thanks_webpacker_goodbye_webpacker
- [ ] webpackでビルドできるようにする（=ファイルのバンドル）
  - 対象フォルダ
    - `app/webpack/packs` 配下
- [ ] バンドルされたファイルをRailsで読み込めるようにする（[参考](https://zenn.dev/hid3/articles/60658bbe935068#%E3%83%90%E3%83%B3%E3%83%89%E3%83%AB%E3%81%95%E3%82%8C%E3%81%9F%E3%83%95%E3%82%A1%E3%82%A4%E3%83%AB%E3%82%92rails%E3%81%A7%E8%AA%AD%E3%81%BF%E8%BE%BC%E3%82%81%E3%82%8B%E3%82%88%E3%81%86%E3%81%AB%E3%81%99%E3%82%8B)）
  - [x] `package.json`内に各種コマンド実行用のnpmスクリプトを書いておく
    - build
    - start
  - [x] ビルド結果をRailsに組み込めるようにする
    - ビルドしたjsを読み込むhelperの作成
      - Simpackerの導入
  - [x] Webpackerが提供している各種メソッドの置き換え
    - javascript_pack_tag
    - stylesheet_pack_tag
- [x] CI上でbuildできるようにする

## 参考

https://zenn.dev/labocho/books/3bb4e81f1e80e3/viewer/552a02
https://techracho.bpsinc.jp/hachi8833/2022_09_06/115289
https://madogiwa0124.hatenablog.com/entry/2020/09/12/164828
https://zenn.dev/hid3/articles/60658bbe935068
